Working full build

diff --git a/server/protos/Makefile b/server/protos/Makefile
--- a/server/protos/Makefile
+++ b/server/protos/Makefile
@@ -1,7 +1,17 @@
 .PHONY: all
 all: build
 
-ROOT := $(shell echo $$(while [ ! -d .git ]; do cd ..; done; pwd))
+define PROTOS_SRC_DIR 
+$(shell echo $$( \
+	while [ ! -d protos_src ]; do \
+		cd ..; \
+		if [ $$(pwd) = '/' ]; then \
+			echo 'protos_src not found' > /dev/stderr; \
+			exit 1; \
+		fi; \
+	done; \
+	pwd)/protos_src)
+endef
 
 GOARCH := $(shell go env GOARCH)
 GOOS := $(shell go env GOOS)
@@ -12,11 +22,11 @@ GOOS := $(shell go env GOOS)
 #   $ go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
 PATH := $(shell echo $$PATH:$$(go env GOPATH)/bin)
 
-*.pb.go: ${ROOT}/protos/*.proto
+*.pb.go: ${PROTOS_SRC_DIR}/*.proto
 	protoc --go_out=. --go_opt=paths=source_relative \
 			--go-grpc_out=. --go-grpc_opt=paths=source_relative \
-			-I ${ROOT}/protos \
-			${ROOT}/protos/*.proto
+			-I ${PROTOS_SRC_DIR} \
+			${PROTOS_SRC_DIR}/*.proto
 
 .PHONY: clean
 clean:
diff --git a/web/pimote/protos/Makefile b/web/pimote/protos/Makefile
--- a/web/pimote/protos/Makefile
+++ b/web/pimote/protos/Makefile
@@ -1,15 +1,25 @@
 all: build
 
-ROOT := $(shell echo $$(while [ ! -d .git ]; do cd ..; done; pwd))
+define PROTOS_SRC_DIR 
+$(shell echo $$( \
+	while [ ! -d protos_src ]; do \
+		cd ..; \
+		if [ $$(pwd) = '/' ]; then \
+			echo 'protos_src not found' > /dev/stderr; \
+			exit 1; \
+		fi; \
+	done; \
+	pwd)/protos_src)
+endef
 
 # Include npm bin,to access protoc-gen-ts_proto
 PATH := $(shell echo $$PATH:$$(npm bin))
 
-*.ts: ${ROOT}/protos/*.proto
+*.ts: ${PROTOS_SRC_DIR}/*.proto
 	echo $$PATH
 	protoc --ts_proto_out=. \
-			-I ${ROOT}/protos \
-			${ROOT}/protos/*.proto
+			-I ${PROTOS_SRC_DIR} \
+			${PROTOS_SRC_DIR}/*.proto
 
 .PHONY: clean
 clean:
